import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { approveAlpha, createMemoryTask, uploadMemories } from '../src/api';
type Selected = { name: string; uri: string; size: number | null; mimeType: string | null };
export default function MemoryUpload() {
  const [selected, setSelected] = useState<Selected | null>(null); const [status, setStatus] = useState('Choose a JSON, JSONL, or ZIP export.'); const [busy, setBusy] = useState(false);
  async function choose() { const result = await DocumentPicker.getDocumentAsync({ type: ['application/json', 'application/zip', 'text/plain'], copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; if (!asset || !/\.(json|jsonl|zip)$/i.test(asset.name)) return setStatus('Unsupported file. Choose JSON, JSONL, or ZIP.'); if ((asset.size ?? 0) > 25 * 1024 * 1024) return setStatus('The first-run upload limit is 25 MB.'); setSelected({ name: asset.name, uri: asset.uri, size: asset.size ?? null, mimeType: asset.mimeType ?? null }); setStatus('Ready: valid rows will stage as passive lineage; questionable rows will be quarantined.'); }
  async function install() { if (!selected) return; setBusy(true); try { setStatus('Reading the selected archive…'); const contentBase64 = await new File(selected.uri).base64(); setStatus('Creating the governed installation task…'); const task = await createMemoryTask(selected.name); await approveAlpha(task.id, selected.name); setStatus('Validating and staging…'); const result = await uploadMemories({ taskId: task.id, fileName: selected.name, mimeType: selected.mimeType, contentBase64 }); setStatus(`${result.preview.stageableRows} passive rows ready/staged; ${result.preview.quarantineRows} quarantined; 0 automatically promoted live.`); } catch (error) { setStatus(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } }
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>GOVERNED INSTALLER</Text><Text style={styles.title}>Install Ashley’s memories</Text><View style={styles.card}><Text style={styles.name}>{selected?.name ?? 'No file selected'}</Text><Text style={styles.body}>{selected?.size ? `${Math.ceil(selected.size / 1024)} KB` : 'Accepted: .json, .jsonl, .zip'}</Text></View><Pressable style={styles.secondary} disabled={busy} onPress={() => void choose()}><Text style={styles.light}>Choose memory file</Text></Pressable><Pressable style={[styles.primary, (!selected || busy) && styles.disabled]} disabled={!selected || busy} onPress={() => void install()}><Text style={styles.dark}>{busy ? 'Installing safely…' : 'Approve and install'}</Text></Pressable><View style={styles.card}><Text style={styles.body}>{status}</Text></View><Text style={styles.guard}>Alpha approval is recorded before staging. Quarantined rows require separate review. Live memory remains untouched.</Text></ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 24, gap: 16, minHeight: '100%' }, eyebrow: { color: '#9999a8', marginTop: 28, letterSpacing: 2 }, title: { color: '#fff', fontSize: 35, fontWeight: '800' }, card: { backgroundColor: '#17171f', borderRadius: 16, padding: 17, gap: 7 }, name: { color: '#fff', fontWeight: '800' }, body: { color: '#c5c5cf', lineHeight: 22 }, primary: { backgroundColor: '#f4f4f6', borderRadius: 16, padding: 17, alignItems: 'center' }, secondary: { borderColor: '#444450', borderWidth: 1, borderRadius: 16, padding: 17, alignItems: 'center' }, light: { color: '#fff', fontWeight: '700' }, dark: { color: '#09090c', fontWeight: '800' }, disabled: { opacity: 0.45 }, guard: { color: '#d6b787', lineHeight: 21 } });
