import { afterEach, describe, expect, it } from 'vitest';
import { buildApp } from '../src/app.js';
const taskInput = { title: 'Install Ashley memories', originalIdea: 'Stage inherited memories as passive lineage.', projectId: 'echo', requestedPermissions: ['MEMORY_SENSITIVE'], estimatedCostPence: 0, affectsProtectedIdentity: false, affectsMemoryGovernance: true, affectsProduction: false, destructive: false };
const apps: Awaited<ReturnType<typeof buildApp>>[] = [];
async function app() { const value = await buildApp(); apps.push(value); return value; }
afterEach(async () => { await Promise.all(apps.splice(0).map((value) => value.close())); });
describe('Echo API', () => {
  it('reports health', async () => { const response = await (await app()).inject({ method: 'GET', url: '/health' }); expect(response.statusCode).toBe(200); expect(response.json().version).toBe('0.4.0'); });
  it('publishes governed capabilities', async () => { const response = await (await app()).inject({ method: 'GET', url: '/v1/system/capabilities' }); expect(response.json().memory.automaticLivePromotion).toBe(false); });
  it('creates an Alpha-gated memory task', async () => { const response = await (await app()).inject({ method: 'POST', url: '/v1/orchestration/tasks', payload: taskInput }); expect(response.statusCode).toBe(201); expect(response.json().state).toBe('AWAITING_ALPHA'); });
  it('refuses upload before Alpha approval', async () => { const server = await app(); const task = (await server.inject({ method: 'POST', url: '/v1/orchestration/tasks', payload: taskInput })).json(); const response = await server.inject({ method: 'POST', url: '/v1/memory/imports/upload', payload: { taskId: task.id, fileName: 'memories.json', contentBase64: Buffer.from('[]').toString('base64'), dryRun: true }}); expect(response.statusCode).toBe(409); });
  it('validates upload after Alpha approval', async () => { const server = await app(); const task = (await server.inject({ method: 'POST', url: '/v1/orchestration/tasks', payload: taskInput })).json(); await server.inject({ method: 'POST', url: `/v1/orchestration/tasks/${task.id}/alpha`, payload: { decision: 'APPROVED', reason: 'Kane approved.' } }); const memories = [{ memory_id: 'm1', content: 'Echo starts with passive inherited memory.' }]; const response = await server.inject({ method: 'POST', url: '/v1/memory/imports/upload', payload: { taskId: task.id, fileName: 'memories.json', contentBase64: Buffer.from(JSON.stringify(memories)).toString('base64'), dryRun: true }}); expect(response.statusCode).toBe(200); expect(response.json().preview.stageableRows).toBe(1); expect(response.json().batch).toBeNull(); });
  it('rejects unsupported upload types', async () => { const server = await app(); const task = (await server.inject({ method: 'POST', url: '/v1/orchestration/tasks', payload: taskInput })).json(); await server.inject({ method: 'POST', url: `/v1/orchestration/tasks/${task.id}/alpha`, payload: { decision: 'APPROVED' } }); const response = await server.inject({ method: 'POST', url: '/v1/memory/imports/upload', payload: { taskId: task.id, fileName: 'memories.txt', contentBase64: Buffer.from('x').toString('base64'), dryRun: true }}); expect(response.statusCode).toBe(400); });
});
